### ISSUE TITLE
iOS Unity においてLobiPostProcessがproject.pbxproj等を占有する問題

### ISSUE THREAD

**Issue by MasashiWada** [kayac/Lobi#206]
iOS Unityの処理でおこなわれるLobi用ポストプロセスの処理にて、Xcodeプロジェクトファイルが更新されますが、その際にファイルをクローズしていないため、続けて別のポストプロセスがXcodeプロジェクトファイルを操作したいときに正常に操作できなくなります。
使用したファイルはクローズをおこなってください。

StreamReader、StreamWriterに対してはdisposeを呼び出すか、usingで自動対応をしてください。

XCProject.csの中にも暗黙的にStreamReaderを経由している箇所があるので判りにくいですが、こういった箇所もdisposeしてください。

(例)
			projectFileInfo = new FileInfo( Path.Combine( this.filePath, "project.pbxproj" ) );
			string contents = null;
			using( var stream = projectFileInfo.OpenText())
				contents = stream.ReadToEnd();

Prime31プラグインのポストプロセスとLobiのポストプロセスを組み合わせると大抵発生すると思います。
元々のXCodeEditorはこういったファイル処理が杜撰で、そのまま使用すると簡単に問題がおきますので、検証をおこなって対応してほしいと思います。

よろしくお願い致します。

**Comment by KAMEDAkyosuke** [comment]
報告ありがとうございます。次のアップデートで対応いたします。
